# Requires secret: MAZERION_PIPELINE_TOKEN
name: "Stage 1: Dev - Formatting"

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: stage1-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Code Formatting Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain (rustfmt)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run cargo check
        run: cargo check --all-targets --all-features

      - name: Report success
        if: success()
        run: echo "✅ Stage 1 (dev) - Formatting checks passed"

  auto-promote:
    name: Auto-promote to lint
    needs: format
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout (for gh context)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create/Find PR dev -> lint and enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.MAZERION_PIPELINE_TOKEN }}
          REPO: ${{ github.repository }}
          HEAD: dev
          BASE: lint
        shell: bash
        run: |
          set -euo pipefail

          PR_URL="$(gh pr create \
            --repo "$REPO" \
            --base "$BASE" \
            --head "$HEAD" \
            --title "Auto-promote: ${HEAD} → ${BASE}" \
            --body "Automatic promotion from Stage 1 (${HEAD}) to Stage 2 (${BASE}). Formatting checks passed." \
            --json url -q .url 2>/dev/null || true)"

          if [ -z "$PR_URL" ]; then
            PR_URL="$(gh pr list --repo "$REPO" --base "$BASE" --head "$HEAD" --state open --json url -q '.[0].url' || true)"
          fi

          if [ -z "$PR_URL" ]; then
            echo "❌ Could not create or locate an open PR for ${HEAD} -> ${BASE}"
            exit 1
          fi

          echo "Using PR: $PR_URL"
          gh pr merge "$PR_URL" --auto --merge --delete-branch=false
